name: build maps

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: dependencies
      run: |-
        pip install -r requirements.txt
        Rscript -e "install.packages('eiPack', repos='https://cran.rstudio.com/')"

    - name: build
      run: make
